project_id = "cuumxmfzhwljylbdlflj"

[functions.gemini-chat]
verify_jwt = false

[functions.content-generator-gemini]
verify_jwt = false

[functions.elevenlabs-voice]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-content]
verify_jwt = false

[functions.speech-analysis]
verify_jwt = false

[functions.writing-feedback]
verify_jwt = false

[functions.openai-chat]
verify_jwt = false

[functions.daily-challenge-generator]
verify_jwt = false

[functions.content-generator]
verify_jwt = false

[functions.translation-service]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.audio-cache]
verify_jwt = false

[functions.pronunciation-analysis]
verify_jwt = false