project_id = "cuumxmfzhwljylbdlflj"

[functions.admin-auth]
verify_jwt = false

[functions.admin-content]
verify_jwt = false

[functions.speech-analysis]
verify_jwt = false

[functions.writing-feedback]
verify_jwt = false