project_id = "cuumxmfzhwljylbdlflj"

[functions.analyze-speaking-suggestion]
verify_jwt = true

[functions.gemini-chat]
verify_jwt = true

[functions.content-generator-gemini]
verify_jwt = true

[functions.elevenlabs-voice]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.admin-auth]
verify_jwt = false

[functions.admin-content]
verify_jwt = false

[functions.speech-analysis]
verify_jwt = true

[functions.writing-feedback]
verify_jwt = false

[functions.openai-chat]
verify_jwt = true

[functions.ielts-writing-examiner]
verify_jwt = false

[functions.openai-test]
verify_jwt = false

[functions.daily-challenge-generator]
verify_jwt = false

[functions.content-generator]
verify_jwt = true

[functions.translation-service]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.audio-cache]
verify_jwt = false

[functions.pronunciation-analysis]
verify_jwt = true

[functions.generate-writing-corrections]
verify_jwt = true

[functions.smart-vocabulary]
verify_jwt = true

[functions.enhanced-speech-analysis]
verify_jwt = true

[functions.audio-cleanup]
verify_jwt = false

[functions.add-to-word-book]
verify_jwt = true

[functions.translate-page]
verify_jwt = false