version: "3.8"

services:
  # Earthworm PostgreSQL Database
  earthworm_db:
    restart: always
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: earthworm
    volumes:
      - earthworm_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - english-aidol-network

  # Earthworm Redis Cache
  earthworm_redis:
    restart: always
    image: redis:7-alpine
    volumes:
      - earthworm_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - english-aidol-network

  # Earthworm Logto PostgreSQL
  earthworm_logto_db:
    restart: always
    image: postgres:14-alpine
    user: root
    volumes:
      - earthworm_logto_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_DB: logto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - english-aidol-network

  # Earthworm Logto Service
  earthworm_logto:
    restart: always
    depends_on:
      earthworm_logto_db:
        condition: service_healthy
    image: svhd/logto:1.18.0
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - "3010:3010"
      - "3011:3011"
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:p0stgr3s@earthworm_logto_db:5432/logto
      - PORT=3010
      - ADMIN_PORT=3011
    networks:
      - english-aidol-network

  # Nginx Reverse Proxy (for production routing)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - earthworm_db
      - earthworm_redis
      - earthworm_logto
    networks:
      - english-aidol-network
    profiles:
      - production

volumes:
  earthworm_data:
    driver: local
  earthworm_redis_data:
    driver: local
  earthworm_logto_data:
    driver: local

networks:
  english-aidol-network:
    driver: bridge

