/**
 * Supported feedback languages for IELTS Writing Test
 * Used in language selector dropdown
 */
export const FEEDBACK_LANGUAGES = [
  { value: "en", label: "English" },
  { value: "zh", label: "中文 (Chinese)" },
  { value: "hi", label: "हिन्दी (Hindi)" },
  { value: "es", label: "Español (Spanish)" },
  { value: "fr", label: "Français (French)" },
  { value: "ar", label: "العربية (Arabic)" },
  { value: "bn", label: "বাংলা (Bengali)" },
  { value: "pt", label: "Português (Portuguese)" },
  { value: "ru", label: "Русский (Russian)" },
  { value: "ja", label: "日本語 (Japanese)" },
  { value: "ur", label: "اردو (Urdu)" },
  { value: "id", label: "Bahasa Indonesia" },
  { value: "de", label: "Deutsch (German)" },
  { value: "vi", label: "Tiếng Việt (Vietnamese)" },
  { value: "tr", label: "Türkçe (Turkish)" },
  { value: "it", label: "Italiano (Italian)" },
  { value: "ko", label: "한국어 (Korean)" },
  { value: "fa", label: "فارسی (Persian)" },
  { value: "ta", label: "தமிழ் (Tamil)" },
  { value: "ne", label: "नेपाली (Nepali)" },
  { value: "th", label: "ไทย (Thai)" },
  { value: "yue", label: "粵語 (Cantonese)" },
  { value: "ms", label: "Bahasa Melayu (Malay)" },
  { value: "te", label: "తెలుగు (Telugu)" },
  { value: "mr", label: "मराठी (Marathi)" },
  { value: "gu", label: "ગુજરાતી (Gujarati)" },
  { value: "kn", label: "ಕನ್ನಡ (Kannada)" },
  { value: "ml", label: "മലയാളം (Malayalam)" },
  { value: "pa", label: "ਪੰਜਾਬੀ (Punjabi)" },
  { value: "or", label: "ଓଡ଼ିଆ (Odia)" },
  { value: "as", label: "অসমীয়া (Assamese)" },
  { value: "sw", label: "Kiswahili (Swahili)" },
  { value: "ha", label: "Hausa" },
  { value: "yo", label: "Yorùbá (Yoruba)" },
  { value: "ig", label: "Ásụ̀sụ́ Ìgbò (Igbo)" },
  { value: "am", label: "አማርኛ (Amharic)" },
  { value: "zu", label: "isiZulu (Zulu)" },
  { value: "af", label: "Afrikaans" },
  { value: "pl", label: "Polski (Polish)" },
  { value: "uk", label: "Українська (Ukrainian)" },
  { value: "ro", label: "Română (Romanian)" },
  { value: "nl", label: "Nederlands (Dutch)" },
  { value: "el", label: "Ελληνικά (Greek)" },
  { value: "cs", label: "Čeština (Czech)" },
  { value: "hu", label: "Magyar (Hungarian)" },
  { value: "sv", label: "Svenska (Swedish)" },
  { value: "bg", label: "Български (Bulgarian)" },
  { value: "sr", label: "Српски (Serbian)" },
  { value: "hr", label: "Hrvatski (Croatian)" },
  { value: "sk", label: "Slovenčina (Slovak)" },
  { value: "no", label: "Norsk (Norwegian)" },
  { value: "da", label: "Dansk (Danish)" },
  { value: "fi", label: "Suomi (Finnish)" },
  { value: "sq", label: "Shqip (Albanian)" },
  { value: "sl", label: "Slovenščina (Slovenian)" },
  { value: "et", label: "Eesti (Estonian)" },
  { value: "lv", label: "Latviešu (Latvian)" },
  { value: "lt", label: "Lietuvių (Lithuanian)" },
  { value: "uz", label: "Oʻzbek (Uzbek)" },
  { value: "kk", label: "Қазақша (Kazakh)" },
  { value: "az", label: "Azərbaycan (Azerbaijani)" },
  { value: "mn", label: "Монгол (Mongolian)" },
  { value: "he", label: "עברית (Hebrew)" },
  { value: "ps", label: "پښتو (Pashto)" },
  { value: "ka", label: "ქართული (Georgian)" },
  { value: "hy", label: "Հայերեն (Armenian)" },
  { value: "tl", label: "Tagalog" },
  { value: "my", label: "မြန်မာ (Burmese)" },
  { value: "km", label: "ភាសាខ្មែរ (Khmer)" },
  { value: "si", label: "සිංහල (Sinhala)" },
] as const;


