
-- Seeding Foundation Grammar Topics
-- Generated by seed-foundations.js

DO $$
DECLARE
    v_topic_id uuid;
    v_lesson_id uuid;
BEGIN

    -- Topic: Sentence Structure: SVO
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('sentence-structure-svo', 'beginner', -99, 'target', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'sentence-structure-svo';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Sentence Structure: SVO', 'The golden rule of English sentences: Subject + Verb + Object. Learn how to build basic sentences correctly.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Sentence Structure: SVO', 
        '
## The Golden Rule: SVO

In English, the order of words is very important. You cannot change the order easily like in some other languages.

The basic "Skeleton" of an English sentence is:

**Subject + Verb + Object**

*   **Subject**: Who is doing the action? (I, You, John, The cat)
*   **Verb**: What is the action? (eat, love, is, run)
*   **Object**: Who receives the action? (an apple, you, the ball)

### Examples
*   ✅ **I love you.** (S + V + O)
*   ❌ **I you love.** (Incorrect)
*   ✅ **John eats apples.**
*   ❌ **Apples eats John.** (Meaning changes or makes no sense)
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Adjectives with Linking Verbs
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('adjectives-linking-verbs', 'beginner', -98, 'star', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'adjectives-linking-verbs';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Adjectives with Linking Verbs', 'Learn how to use "is", "feel", "look" with adjectives to describe things.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Adjectives with Linking Verbs', 
        '
## Describing Things (Linking Verbs)

Usually, a verb is an *action* (run, eat). But some verbs are **Linking Verbs**. They connect the Subject to a description (Adjective).

**Subject + Linking Verb + Adjective**

Common Linking Verbs:
*   **Be (am, is, are)**
*   **Feel**
*   **Look**
*   **Smell**
*   **Taste**
*   **Sound**

### Examples
*   ✅ **She is happy.** (Not "She is happiness")
*   ✅ **You look tired.**
*   ✅ **It smells good.** (Not "It smells well")
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Word Order: Place & Time
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('word-order-time-place', 'beginner', -97, 'book', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'word-order-time-place';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Word Order: Place & Time', 'When do you say "at 6 PM"? Learn the correct order for Place and Time in a sentence.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Word Order: Place & Time', 
        '
## Place Before Time

In English, if you have both a **Place** (where) and a **Time** (when) in a sentence, the Place usually comes first.

**Subject + Verb + Place + Time**

Rule: **P.T.** (Place, then Time).

### Examples
*   ✅ **I go *to the park* *at 6 PM*.**
*   ❌ **I go *at 6 PM* *to the park*.** (Sounds unnatural)
*   ✅ **We arrived *here* *yesterday*.**
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Adjective Placement
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('adjective-placement', 'beginner', -96, 'target', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'adjective-placement';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Adjective Placement', 'Where do adjectives go? Before or after the noun? Learn the rule.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Adjective Placement', 
        '
## Before the Noun

In many languages (like Spanish or French), the adjective comes *after* the noun (Car red).
In **English**, the adjective comes **BEFORE** the noun.

**Adjective + Noun**

### Examples
*   ✅ **A *red* car.**
*   ❌ **A car *red*.**
*   ✅ **A *happy* man.**
*   ✅ **An *expensive* house.**

Note: If you use "is/are", the adjective comes after the verb (The car is red), but if it is attached to the noun directly, it must be before.
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Plural Nouns (Regular & Irregular)
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('plural-nouns', 'beginner', -95, 'book', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'plural-nouns';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Plural Nouns (Regular & Irregular)', 'One cat, two cats. Build plurals correctly, including the tricky irregular ones.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Plural Nouns (Regular & Irregular)', 
        '
## Making Things Plural

### Regular Plurals (+s / +es)
Most words just add **-s**.
*   Dog -> Dogs
*   Car -> Cars

Words ending in -s, -sh, -ch, -x add **-es**.
*   Bus -> Buses
*   Watch -> Watches

### Irregular Plurals (Memorize these!)
Some words change completely. DO NOT add ''s''.
*   **Child -> Children** (Not "childs")
*   **Person -> People** (Not "persons")
*   **Man -> Men**
*   **Woman -> Women**
*   **Foot -> Feet**
*   **Tooth -> Teeth**
*   **Mouse -> Mice**
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Possession: 's vs OF
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('possessives-s-vs-of', 'beginner', -94, 'zap', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'possessives-s-vs-of';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Possession: ''s vs OF', 'When to say "John''s car" and when to say "The door of the house".')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Possession: ''s vs OF', 
        '
## ''s vs OF

How do we show possession (who owns what)?

### 1. Use ''s for People and Animals
*   ✅ **John''s car.**
*   ❌ **The car of John.** (Grammatically okay but sounds very unnatural)
*   ✅ **My mother''s house.**
*   ✅ **The cat''s toy.**

### 2. Use OF for Things / Inanimate Objects
*   ✅ **The door of the house.**
*   ❌ **The house''s door.** (Usually avoiding ''s for objects)
*   ✅ **The end of the movie.**
*   ✅ **The capital of France.**
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Yes/No Questions
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('basic-questions-yes-no', 'beginner', -93, 'trophy', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'basic-questions-yes-no';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Yes/No Questions', 'How to ask simple questions using Do, Does, Is, and Are.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Yes/No Questions', 
        '
## The Helper Verb Strategy

To ask a Yes/No question in English, you cannot just raise your voice. You usually need a **Helper Verb** at the start.

### 1. With "To Be" (Am, Is, Are) -> Invert
Swap the Subject and Verb.
*   Statement: **You are** happy.
*   Question: **Are you** happy?

### 2. With Action Verbs -> Use DO / DOES
You need "Do" (I/You/We/They) or "Does" (He/She/It).
*   Statement: **You like** pizza.
*   Question: **Do you like** pizza?
*   Statement: **She lives** here.
*   Question: **Does she live** here? (Note: "lives" becomes "live" because "Does" takes the ''s'')
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Wh- Questions
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('basic-questions-wh', 'beginner', -92, 'target', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'basic-questions-wh';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Wh- Questions', 'Who, What, Where, When, Why, How. Learn the correct word order.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Wh- Questions', 
        '
## Asking for Information (Wh-)

To ask for information, put the **Wh- word** at the very beginning. Then follow the Yes/No rule.

**Wh-Word + Helper + Subject + Verb?**

### Structure
1.  **Wh** (Where)
2.  **Helper** (do)
3.  **Subject** (you)
4.  **Verb** (live)
-> **Where do you live?**

### Examples
*   **What** is your name?
*   **When** does the train leave?
*   **Why** are you crying?
*   **How** do you cook this?
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Conjunctions: And, But, So, Because
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('conjunctions-basics', 'beginner', -91, 'star', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'conjunctions-basics';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Conjunctions: And, But, So, Because', 'Connect your simple sentences together to make longer thoughts.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Conjunctions: And, But, So, Because', 
        '
## Glue Words

Use these words to connect two ideas.

### And (Addition)
*   I like coffee **and** I like tea.

### But (Contrast / Surprise)
*   I like coffee, **but** I don''t like tea.
*   He is small, **but** he is strong.

### So (Result)
*   It was raining, **so** took an umbrella.

### Because (Reason)
*   I took an umbrella **because** it was raining.
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Feelings: To Be vs To Have
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('to-be-vs-to-have', 'beginner', -90, 'book', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'to-be-vs-to-have';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Feelings: To Be vs To Have', 'Stop saying "I have hunger". Learn which feelings use "To Be" in English.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Feelings: To Be vs To Have', 
        '
## The "Have" Trap

In many languages (Spanish, French, Portuguese, Italian), you say "I have hunger" or "I have cold".
In **English**, these are states of being. You use **TO BE**.

**Subject + Am/Is/Are + Adjective**

### Common Mistakes
*   ❌ I have hunger. -> ✅ **I am hungry.**
*   ❌ I have thirst. -> ✅ **I am thirsty.**
*   ❌ I have cold. -> ✅ **I am cold.**
*   ❌ I have hot. -> ✅ **I am hot.**
*   ❌ I have fear. -> ✅ **I am afraid.**
*   ❌ I have 20 years. -> ✅ **I am 20 years old.** (Very important!)
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Adjective Order
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('adjective-order', 'beginner', -89, 'zap', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'adjective-order';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Adjective Order', 'Big red car or Red big car? Learn the secret rule native speakers use.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Adjective Order', 
        '
## The Order of Description

When you have more than one adjective, they must go in a specific order. Native speakers do this naturally, but you must learn it.

**Opinion -> Size -> Age -> Shape -> Color -> Origin -> Material -> Purpose**

A simple version to remember: **Size - Age - Color**

### Examples
*   ✅ A **big red** bus. (Size, then Color)
*   ❌ A **red big** bus.
*   ✅ A **beautiful old Italian** house. (Opinion, Age, Origin)
*   ✅ A **small round** table.
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: This, That, These, Those
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('demonstratives', 'beginner', -88, 'target', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'demonstratives';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'This, That, These, Those', 'Pointing at the world. Learn the difference between singular/plural and near/far.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'This, That, These, Those', 
        '
## Pointing Words

We choose the word based on **Distance** (Near/Far) and **Number** (One/Many).

| | Near (Here) | Far (There) |
|---|---|---|
| **Singular (1)** | **This** | **That** |
| **Plural (2+)** | **These** | **Those** |

### Examples
*   **This** is my phone. (Holding it)
*   **That** is my car. (Pointing across the street)
*   **These** are my keys. (Holding them)
*   **Those** are the birds. (Flying in the sky)
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: He/She/It (The S Rule)
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('subject-verb-agreement', 'beginner', -87, 'trophy', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'subject-verb-agreement';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'He/She/It (The S Rule)', 'The most common mistake: forgetting the S. He runs, She eats.')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'He/She/It (The S Rule)', 
        '
## Generally, Add ''S''

In the Present Simple tense, for **He, She, It** (and singular names like John, The Cat), you MUST add an **-s** to the verb.

*   I play -> **He plays**
*   You eat -> **She eats**
*   We work -> **It works**

### Exceptions
*   **Have -> Has** (Not "haves")
*   **Go -> Goes**
*   **Do -> Does**
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: There is vs It is
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('there-is-vs-it-is', 'beginner', -86, 'star', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'there-is-vs-it-is';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'There is vs It is', 'Do not confuse existence ("There is a dog") with definition ("It is a dog").')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'There is vs It is', 
        '
## Existence vs Identification

### There is / There are
Use this to say something **exists** or is located somewhere. "Presentar" algo.
*   ✅ **There is** a spider in the bathroom.
*   ✅ **There are** many people here.

### It is
Use this to **identify** or **describe** a specific thing you already mentioned or see.
*   What is that noise? **It is** the wind.
*   I like this car. **It is** fast.

### Comparison
*   **There is** a problem. (A problem exists)
*   **It is** a problem. (Identifying a specific situation as a problem)
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Frequency Adverbs (Always, Never)
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('frequency-adverbs', 'beginner', -85, 'book', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'frequency-adverbs';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Frequency Adverbs (Always, Never)', 'Where do you put "always"? Before or after the verb? It depends!')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Frequency Adverbs (Always, Never)', 
        '
## Before the Action, After the Be

Words like **Always, Usually, Often, Sometimes, Never** tell us "How Often".

### Rule 1: Before Action Verbs
Put it **BEFORE** the main verb.
*   ✅ I **always** drink coffee.
*   ❌ I drink **always** coffee.
*   ✅ She **never** listens.

### Rule 2: After "To Be"
Put it **AFTER** am/is/are.
*   ✅ I am **always** happy.
*   ❌ I **always** am happy.
*   ✅ He is **never** late.
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

    -- Topic: Object Placement
    INSERT INTO grammar_topics (slug, level, topic_order, icon, color, is_published)
    VALUES ('object-pronouns-placement', 'beginner', -84, 'zap', 'emerald', true)
    ON CONFLICT (slug) DO UPDATE SET 
        level = EXCLUDED.level,
        topic_order = EXCLUDED.topic_order
    RETURNING id INTO v_topic_id;

    -- If updated and not returned (because no change?), force get ID.
    IF v_topic_id IS NULL THEN
        SELECT id INTO v_topic_id FROM grammar_topics WHERE slug = 'object-pronouns-placement';
    END IF;


    INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
    VALUES (v_topic_id, 'en', 'Object Placement', 'Stop separating the verb and the object. "I like it very much", not "I like very much it".')
    ON CONFLICT (topic_id, language_code) DO UPDATE SET 
        title = EXCLUDED.title,
        description = EXCLUDED.description;

    -- Check for existing lesson manually because there is no unique constraint on (topic_id, lesson_order)
    v_lesson_id := NULL;
    SELECT id INTO v_lesson_id FROM grammar_lessons WHERE topic_id = v_topic_id AND lesson_order = 1 LIMIT 1;

    IF v_lesson_id IS NULL THEN
        INSERT INTO grammar_lessons (topic_id, lesson_order)
        VALUES (v_topic_id, 1)
        RETURNING id INTO v_lesson_id;
    END IF;

    INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)

    VALUES (
        v_lesson_id, 
        'en', 
        'Object Placement', 
        '
## Glue the Object

In English, the **Verb** and the **Object** contain a very strong magnetic connection. You generally CANNOT separate them.

**Verb + Object**

Adverbs (like ''very much'', ''a lot'', ''well'') usually go at the **END** of the sentence.

### Examples
*   ✅ I [like] [pizza] **very much**.
*   ❌ I [like] **very much** [pizza].
*   ✅ He [speaks] [English] **well**.
*   ❌ He [speaks] **well** [English].
*   ✅ I [love] [it].
', 
        'Coming soon...', 
        'Coming soon...', 
        'Coming soon...', 
        'Start with the basics!', 
        '[]'::jsonb, 
        '[]'::jsonb
    )
    ON CONFLICT (lesson_id, language_code) DO UPDATE SET 
        theory_definition = EXCLUDED.theory_definition;

END $$;
