
-- Updating Content for Foundation Topics
-- Generated by manual-seed-content.js

DO $$
DECLARE
    v_lesson_id uuid;
BEGIN

    -- Updating sentence-structure-svo (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## The Golden Rule: SVO

In English, clarity comes from order. Unlike some languages where word order is flexible, English is strict.

The basic "Skeleton" of almost every sentence is:

**Subject + Verb + Object**

*   **Subject (S)**: The ''doer'' (I, She, The cat).
*   **Verb (V)**: The action (eat, likes, is).
*   **Object (O)**: The receiver (pizza, him, the ball).

If you mess up this order, you sound confused or like Yoda!',
        theory_formation = '### Formula

| Subject | Verb | Object (Optional) |
| :--- | :--- | :--- |
| I | love | you. |
| John | eats | an apple. |
| The bus | arrived. | (No object) |',
        theory_usage = '*   **Status:** The most important rule in English.
*   **When:** All the time, for statements.
*   **Why:** English uses order to show who does what. "John loves Mary" is totally different from "Mary loves John".',
        theory_common_mistakes = '*   ❌ **I you love.** (Putting object before verb)
*   ❌ **Eats John an apple.** (Putting verb first - unless it''s a question)
*   ❌ **Yesterday came my friend.** (Subject must usually come before verb -> *My friend came yesterday*)',
        localized_tips = 'Think of the Subject as the driver and the Verb as the car. The driver must get in before the car moves!'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'sentence-structure-svo')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Sentence Structure: SVO'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'sentence-structure-svo');

    -- Updating sentence-structure-svo (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'sentence-structure-svo')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Cấu trúc câu: SVO',
            '## Quy tắc vàng: SVO

Trong tiếng Anh, thứ tự từ rất quan trọng. "Bộ xương" cơ bản của hầu hết mọi câu là:

**Subject (Chủ ngữ) + Verb (Động từ) + Object (Tân ngữ)**

*   **Subject**: Người thực hiện hành động (I, She, The cat).
*   **Verb**: Hành động (eat, likes, is).
*   **Object**: Người/vật nhận hành động (pizza, him, the ball).',
            '### Công thức

| Chủ ngữ | Động từ | Tân ngữ |
| :--- | :--- | :--- |
| I | love | you. |
| John | eats | an apple. |
| The bus | arrived. | (Không có tân ngữ) |',
            '*   **Khi nào:** Hầu như tất cả các câu khẳng định.
*   **Tại sao:** "John loves Mary" (John yêu Mary) rất khác với "Mary loves John" (Mary yêu John).',
            '*   ❌ **I you love.** (Sai trật tự)
*   ❌ **Yesterday came my friend.** (Chủ ngữ phải đứng trước động từ -> *My friend came yesterday*)',
            'SVO là vua! Luôn nhớ: Ai (S) làm gì (V) cho ai/cái gì (O).',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'sentence-structure-svo'),
            'vi',
            'Cấu trúc câu: SVO',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating adjectives-linking-verbs (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## Describing Things

Usually, verbs are actions (run, jump). But "Linking Verbs" are different. They act like an equals sign (=). They connect the subject to an adjective describing it.

**Subject + Linking Verb + Adjective**',
        theory_formation = '### Common Linking Verbs

1.  **To Be**: am, is, are, was, were
2.  **Sense Verbs**: look, feel, smell, taste, sound
3.  **Change Verbs**: become, get',
        theory_usage = 'Use these when you want to describe a **state** or **condition**, not an action.',
        theory_common_mistakes = '*   ❌ **She sings good.** (Use adverb ''well'' for actions)
*   ❌ **I feel happily.** (With linking verbs, use Adjectives, not Adverbs)
*   ✅ **I feel happy.**
*   ✅ **She looks tired.**',
        localized_tips = 'If you can replace the verb with ''IS'' and it makes sense, it''s a linking verb! (You look tired -> You ARE tired).'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'adjectives-linking-verbs')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Adjectives with Linking Verbs'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'adjectives-linking-verbs');

    -- Updating adjectives-linking-verbs (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'adjectives-linking-verbs')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Tính từ & Động từ nối',
            '## Mô tả sự vật

Động từ thường chỉ hành động. Nhưng "Linking Verbs" (Động từ nối) hoạt động giống như dấu bằng (=). Chúng nối chủ ngữ với tính từ mô tả nó.

**Chủ ngữ + Linking Verb + Tính từ**',
            '### Các từ phổ biến

1.  **To Be**: am, is, are
2.  **Giác quan**: look (trông), feel (cảm thấy), smell (ngửi), taste (nếm), sound (nghe)
3.  **Thay đổi**: become (trở nên), get (trở nên)',
            'Dùng để mô tả trạng thái, cảm giác.',
            '*   ❌ **I feel happily.** (Sai! Sau linking verb phải là Tính từ)
*   ✅ **I feel happy.**
*   ✅ **It tastes good.** (Không phải ''well'')',
            'Nếu bạn có thể thay thế động từ bằng ''thì/là'' (IS), đó là linking verb.',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'adjectives-linking-verbs'),
            'vi',
            'Tính từ & Động từ nối',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating word-order-time-place (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## Place Before Time

When you need to say WHERE and WHEN something happened, English has a strict preference:

**Place + Time**

Think of specific details first (where), then general context (when).',
        theory_formation = '### Structure
**Subject + Verb + [WHERE] + [WHEN]**

*   I go **[to school] [every day]**.
*   We arrived **[at the airport] [at 2 PM]**.',
        theory_usage = 'Used in standard sentences involving both location and time.',
        theory_common_mistakes = '*   ❌ **I go every day to school.** (Don''t put time in the middle)
*   ❌ **I saw at the party him.** (Keep verb and object together!) -> **I saw him at the party.**',
        localized_tips = 'Remember **P.T.** (Place -> Time). Just like a P.T. (Personal Trainer)!'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'word-order-time-place')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Word Order: Place & Time'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'word-order-time-place');

    -- Updating word-order-time-place (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'word-order-time-place')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Trật tự từ: Nơi chốn & Thời gian',
            '## Nơi chốn trước, Thời gian sau

Khi bạn muốn nói Ở ĐÂU và KHI NÀO, tiếng Anh có quy tắc:

**Nơi chốn (Place) + Thời gian (Time)**',
            '### Cấu trúc
**Chủ ngữ + Động từ + [Ở Đâu] + [Khi Nào]**

*   I go **[to school] [every day]**.
*   We arrived **[at the airport] [at 2 PM]**.',
            'Dùng trong hầu hết các câu.',
            '*   ❌ **I go every day to school.** (Sai! Đừng chèn thời gian vào giữa)
*   ✅ **I go to school every day.**',
            'Hãy nhớ quy tắc **P.T.** (Place trước, Time sau).',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'word-order-time-place'),
            'vi',
            'Trật tự từ: Nơi chốn & Thời gian',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating adjective-placement (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## Before the Noun

In English, adjectives (words that describe) are surprisingly stubborn. They almost ALWAYS go **before** the noun they describe.

**Adjective + Noun**',
        theory_formation = '*   **Red** car (Not ''car red'')
*   **Big** house
*   **Interesting** book

However, if using ''to be'', they go after:
*   The car is **red**.',
        theory_usage = 'Describing any object, person, or idea.',
        theory_common_mistakes = '*   ❌ **I have a car blue.** (Spanish/French style)
*   ✅ **I have a blue car.**',
        localized_tips = 'Adjectives are shy; they like to hide behind the noun (just kidding, they stand in front to protect it!).'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'adjective-placement')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Adjective Placement'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'adjective-placement');

    -- Updating adjective-placement (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'adjective-placement')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Vị trí của Tính từ',
            '## Trước Danh từ

Trong tiếng Việt, ta nói "xe đỏ". Trong tiếng Anh, ta nói "đỏ xe" (red car). Tính từ luôn đứng **TRƯỚC** danh từ.

**Tính từ + Danh từ**',
            '*   **Red** car
*   **Beautiful** girl
*   **Hot** coffee',
            'Dùng để miêu tả.',
            '*   ❌ **I like coffee hot.**
*   ✅ **I like hot coffee.**
*   (Nhưng: The coffee is hot - OK)',
            'Tiếng Anh ngược với tiếng Việt: Tính từ đi trước!',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'adjective-placement'),
            'vi',
            'Vị trí của Tính từ',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating plural-nouns-regular-irregular (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## More Than One

When we talk about more than one thing, we usually add **-s**. But, English loves drama, so there are many exceptions!

*   One cat -> Two cats
*   One bus -> Two buses',
        theory_formation = '### The Rules

1.  **Regular**: Add **-s** (dog -> dogs)
2.  **Ending in -s, -sh, -ch, -x**: Add **-es** (box -> boxes, watch -> watches)
3.  **Ending in -y**: Change to **-ies** (baby -> babies) *unless there is a vowel before y (boy -> boys)*
4.  **Irregular**: Complete change (man -> men, child -> children, foot -> feet)',
        theory_usage = 'Used whenever counting items > 1.',
        theory_common_mistakes = '*   ❌ **Childs.** -> ✅ **Children**
*   ❌ **Peoples.** -> ✅ **People**
*   ❌ **The police is...** -> ✅ **The police are...** (Police is always plural!)',
        localized_tips = 'Memories the "super irregularities" first: Men, Women, Children, People, Teeth, Feet.'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'plural-nouns-regular-irregular')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Plural Nouns'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'plural-nouns-regular-irregular');

    -- Updating plural-nouns-regular-irregular (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'plural-nouns-regular-irregular')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Danh từ số nhiều',
            '## Hơn một sự vật

Trong tiếng Việt, ta dùng "những", "các". Trong tiếng Anh, ta thêm **-s**. Nhưng có nhiều ngoại lệ!

*   One cat -> Two cats
*   One bus -> Two buses',
            '### Quy tắc

1.  **Thường**: Thêm **-s** (dog -> dogs)
2.  **Tận cùng -s, -sh, -ch, -x**: Thêm **-es** (box -> boxes)
3.  **Tận cùng -y**: Đổi thành **-ies** (baby -> babies) *trừ khi trước y là nguyên âm (boy -> boys)*
4.  **Bất quy tắc (Học thuộc)**: man -> men, child -> children, foot -> feet',
            'Dùng khi đếm số lượng > 1.',
            '*   ❌ **Childs.** -> ✅ **Children**
*   ❌ **The police is...** -> ✅ **The police are...** (Cảnh sát luôn là số nhiều!)',
            'Học thuộc lòng những từ siêu bất quy tắc: Men, Women, Children, People, Teeth, Feet.',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'plural-nouns-regular-irregular'),
            'vi',
            'Danh từ số nhiều',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating possession-s-vs-of (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## Whose is it?

To show ownership, we have two main ways: **''s** (Apostrophe S) and **OF**.

*   **''s**: Used mostly for PEOPLE and ANIMALS.
*   **OF**: Used mostly for THINGS and IDEAS.',
        theory_formation = '*   **John''s** car (Person)
*   The cat**''s** toy (Animal)
*   The door **of** the house (Thing)
*   The end **of** the movie (Abstract)',
        theory_usage = 'Showing who owns what.',
        theory_common_mistakes = '*   ❌ **The car of John.** (Too French/Spanish!)
*   ✅ **John''s car.**
*   ❌ **The house''s door.** (A bit unnatural)
*   ✅ **The door of the house.**',
        localized_tips = 'Humans get the ''S''!'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'possession-s-vs-of')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Possession: ''s vs OF'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'possession-s-vs-of');

    -- Updating possession-s-vs-of (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'possession-s-vs-of')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Sở hữu: ''s hay OF',
            '## Của ai?

Để chỉ sự sở hữu, có 2 cách chính: **''s** và **OF**.

*   **''s**: Dùng cho CON NGƯỜI và ĐỘNG VẬT.
*   **OF**: Dùng cho ĐỒ VẬT và Ý TƯỞNG.',
            '*   **John''s** car (Xe của John)
*   The cat**''s** toy (Đồ chơi của mèo)
*   The door **of** the house (Cửa của ngôi nhà)',
            'Chỉ sự sở hữu.',
            '*   ❌ **The car of John.** (Nghe rất tây nhưng... sai!)
*   ✅ **John''s car.**',
            'Người thì dùng ''s. Vật thì dùng OF.',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'possession-s-vs-of'),
            'vi',
            'Sở hữu: ''s hay OF',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating yes-no-questions (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## Asking for Confirmation

These are questions you can answer with just a nod (Yes) or a shake of the head (No). In English, you usually need a **Helper Verb** (Auxiliary) to start the question.

**Helper + Subject + Verb?**',
        theory_formation = '### Standard Verbs (Do/Does)
*   **Do** you typically like pizza?
*   **Does** she work here?

### To Be (Am/Is/Are)
*   **Are** you happy?
*   **Is** he strong?

### Can/Should/Will
*   **Can** you swim?',
        theory_usage = 'Asking for confirmation.',
        theory_common_mistakes = '*   ❌ **You like pizza?** (Intonation question - informal, but grammatically weak)
*   ✅ **Do you like pizza?**
*   ❌ **Live you here?** (Old English style, incorrect now)
*   ✅ **Do you live here?**',
        localized_tips = 'Don''t just raise your voice at the end! Use ''DO'' or ''ARE'' at the start.'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'yes-no-questions')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Yes/No Questions'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'yes-no-questions');

    -- Updating yes-no-questions (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'yes-no-questions')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Câu hỏi Yes/No',
            '## Hỏi xác nhận

Đây là những câu hỏi chỉ cần trả lời Có hoặc Không. Trong tiếng Anh, bạn CẦN trợ động từ đứng đầu câu.

**Trợ động từ + Chủ ngữ + Động từ?**',
            '### Động từ thường (mượn Do/Does)
*   **Do** you like pizza?
*   **Does** she work here?

### Động từ To Be (Đảo ngữ)
*   **Are** you happy?
*   **Is** he strong?',
            'Xác nhận thông tin.',
            '*   ❌ **You like pizza?** (Câu hỏi ngữ điệu - chỉ dùng văn nói suồng sã)
*   ✅ **Do you like pizza?**
*   ❌ **Live you here?** (Sai ngữ pháp nghiêm trọng)
*   ✅ **Do you live here?**',
            'Đừng chỉ lên giọng cuối câu như tiếng Việt. Hãy ''quăng'' Do/Does/Am/Is/Are ra đầu câu!',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'yes-no-questions'),
            'vi',
            'Câu hỏi Yes/No',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating wh-questions (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## Information Questions

When ''Yes'' or ''No'' isn''t enough, we use Wh- words. The structure is almost the same as Yes/No questions, just put the **Wh- Word** at the very front.

**Wh- + Helper + Subject + Verb?**',
        theory_formation = '### The Wh- Words
*   **Who** (Person)
*   **What** (Thing)
*   **Where** (Place)
*   **When** (Time)
*   **Why** (Reason)
*   **How** (Method)

### Examples
*   **Where** do you live?
*   **What** are you doing?
*   **Why** is he crying?',
        theory_usage = 'Asking for specific details.',
        theory_common_mistakes = '*   ❌ **Where you go?** (Missing helper)
*   ✅ **Where DO you go?**
*   ❌ **What means this word?**
*   ✅ **What DOES this word mean?**',
        localized_tips = 'Wh- word first, then the ''muscle'' word (helper), then the person, then the action.'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'wh-questions')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Wh- Questions'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'wh-questions');

    -- Updating wh-questions (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'wh-questions')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Câu hỏi Wh-',
            '## Hỏi thông tin

Khi ''Có'' hoặc ''Không'' là chưa đủ. Cấu trúc giống hệt câu hỏi Yes/No, chỉ cần đặt từ để hỏi lên đầu.

**Từ để hỏi + Trợ động từ + Chủ ngữ + Động từ?**',
            '### Các từ để hỏi
*   **Who** (Ai)
*   **What** (Cái gì)
*   **Where** (Ở đâu)
*   **When** (Khi nào)
*   **Why** (Tại sao)
*   **How** (Như thế nào)

### Ví dụ
*   **Where** do you live?
*   **What** are you doing?',
            'Hỏi chi tiết.',
            '*   ❌ **Where you go?** (Thiếu trợ động từ)
*   ✅ **Where DO you go?**
*   ❌ **What means this?**
*   ✅ **What DOES this mean?**',
            'Từ để hỏi -> Trợ động từ -> Chủ ngữ -> Động từ.',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'wh-questions'),
            'vi',
            'Câu hỏi Wh-',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating conjunctions-intro (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## Glue Words

Conjunctions glue two ideas together. Without them, we speak in short, robot sentences.

*   **And**: Addition (+)
*   **But**: Contrast (-)
*   **So**: Result (->)
*   **Because**: Reason (<-)',
        theory_formation = '*   I like tea **and** coffee.
*   I like tea, **but** I hate coffee.
*   I was tired, **so** I slept.
*   I slept **because** I was tired.',
        theory_usage = 'Connecting simple sentences to make complex ones.',
        theory_common_mistakes = '*   Starting every sentence with ''And'' or ''But'' in formal writing (Avoid it).
*   Confusing ''So'' (Result) vs ''Because'' (Reason).',
        localized_tips = '**So** looks forward (to the result). **Because** looks backward (to the cause).'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'conjunctions-intro')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Conjunctions (And, But, So, Because)'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'conjunctions-intro');

    -- Updating conjunctions-intro (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'conjunctions-intro')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Liên từ (And, But, So, Because)',
            '## Từ nối

Liên từ giúp nối các ý lại với nhau. Không có nó, bạn nói như robot.

*   **And**: Và (+)
*   **But**: Nhưng (-)
*   **So**: Nên/Vì vậy (->)
*   **Because**: Bởi vì (<-)',
            '*   I like tea **and** coffee.
*   I like tea, **but** I hate coffee.
*   I was tired, **so** I slept. (Mệt -> Ngủ)
*   I slept **because** I was tired. (Ngủ <- Vì mệt)',
            'Nối câu đơn thành câu ghép.',
            '*   Nhầm lẫn ''So'' và ''Because''. ''So'' chỉ kết quả, ''Because'' chỉ lý do.',
            '**So** hướng về tương lai (kết quả). **Because** nhìn về quá khứ (lý do).',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'conjunctions-intro'),
            'vi',
            'Liên từ (And, But, So, Because)',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating feelings-to-be-vs-to-have (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## I am Hungry (Not I Have Hunger)

In many languages (Spanish, French, etc.), you "have" hunger or "have" cold. In English, you **ARE** these things because they are adjectives describing your state.

**Subject + To Be + Adjective**',
        theory_formation = '*   ✅ **I am** hungry.
*   ✅ **I am** cold.
*   ✅ **I am** afraid.
*   ✅ **I am** 20 years old. (Important!)',
        theory_usage = 'Describing physical or emotional states.',
        theory_common_mistakes = '*   ❌ **I have hunger.**
*   ❌ **I have cold.**
*   ❌ **I have 20 years.** (Very common mistake!) -> ✅ **I am 20.**',
        localized_tips = '''Hungry'', ''Cold'', ''Afraid'' are Adjectives in English, not Nouns. So use ''TO BE''.'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'feelings-to-be-vs-to-have')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Feelings: To Be vs To Have'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'feelings-to-be-vs-to-have');

    -- Updating feelings-to-be-vs-to-have (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'feelings-to-be-vs-to-have')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Cảm xúc: To Be vs To Have',
            '## I am Hungry (Không phải I Have Hunger)

Trong nhiều ngôn ngữ, người ta nói "tôi có đói". Trong tiếng Anh, đói/lạnh/sợ là TÍNH TỪ. Vì vậy bạn phải dùng động từ **TO BE**.

**Subject + To Be + Adjective**',
            '*   ✅ **I am** hungry. (Tôi thì đói)
*   ✅ **I am** cold. (Tôi thì lạnh)
*   ✅ **I am** 20 years old. (Tôi thì 20 tuổi)',
            'Mô tả trạng thái cơ thể/tâm lý.',
            '*   ❌ **I have hunger.**
*   ❌ **I have 20 years.** (Sai lầm kinh điển!) -> ✅ **I am 20.**',
            'Trong tiếng Anh, bạn ''LÀ'' tuổi của bạn, bạn không ''CÓ'' nó.',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'feelings-to-be-vs-to-have'),
            'vi',
            'Cảm xúc: To Be vs To Have',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating adjective-order (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## The Secret Code

Did you know English speakers instinctively order adjectives? A "green big dragon" sounds wrong. It must be a "big green dragon".

**O.S.A.S.C.O.M.P.**
Opinion -> Size -> Age -> Shape -> Color -> Origin -> Material -> Purpose',
        theory_formation = '1.  **Opinion**: Good, ugly
2.  **Size**: Big, small
3.  **Age**: Old, new
... 
5.  **Color**: Red, blue

*   ✅ A **lovely little old** house.
*   ❌ An **old lovely little** house.',
        theory_usage = 'When using 2+ adjectives.',
        theory_common_mistakes = '*   Putting color before size. (Red big ball ❌ -> Big red ball ✅)',
        localized_tips = 'Size usually comes first. Color usually comes close to the noun. "Big Red Bus".'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'adjective-order')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Adjective Order'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'adjective-order');

    -- Updating adjective-order (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'adjective-order')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Trật tự tính từ',
            '## Mật mã ngầm

Người bản xứ luôn sắp xếp tính từ theo một trật tự nhất định mà đôi khi họ không nhận ra. "Green big dragon" nghe rất sai. Phải là "Big green dragon".

**O.S.A.S.C.O.M.P.**
Quan điểm -> Kích thước -> Tuổi -> Hình dáng -> Màu -> Nguồn gốc -> Chất liệu',
            '1.  **Quan điểm**: Good, beautiful
2.  **Kích thước**: Big, small
3.  **Tuổi**: Old, new
... 
5.  **Màu**: Red, blue

*   ✅ A **lovely little old** house.',
            'Khi dùng 2 tính từ trở lên.',
            '*   Đặt màu trước kích thước. (Red big ball ❌ -> Big red ball ✅)',
            'Kích thước thường đi trước. Màu sắc thường đứng sát danh từ. "Big Red Bus".',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'adjective-order'),
            'vi',
            'Trật tự tính từ',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating this-that-these-those (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## Pointing Fingers

These words act like a finger pointing at something. We choose the word based on **Distance** (Near/Far) and **Number** (One/Many).',
        theory_formation = '| | Near (Here) | Far (There) |
| :--- | :--- | :--- |
| **Singular (1)** | **This** is a cat. | **That** is a star. |
| **Plural (>1)** | **These** are cats. | **Those** are stars. |',
        theory_usage = 'Identifying specific objects relative to you.',
        theory_common_mistakes = '*   ❌ **These is my friend.** (These = Plural -> These **ARE**)
*   ❌ **I like that shoes.** (Shoes = Plural -> **Those** shoes)',
        localized_tips = '**Th**is/**Th**ese have a ''h'' sound like **H**ere. **Th**at/**Th**ose point away.'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'this-that-these-those')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'This, That, These, Those'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'this-that-these-those');

    -- Updating this-that-these-those (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'this-that-these-those')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'This, That, These, Those',
            '## Chỉ trỏ

Chúng ta chọn từ dựa trên **Khoảng cách** (Gần/Xa) và **Số lượng** (Ít/Nhiều).',
            '| | Gần (Đây) | Xa (Đó/Kia) |
| :--- | :--- | :--- |
| **Số ít (1)** | **This** (Cái này) | **That** (Cái kia) |
| **Số nhiều (>1)** | **These** (Những cái này) | **Those** (Những cái kia) |',
            'Chỉ định danh sự vật.',
            '*   ❌ **These is...** (These đi với Are)
*   ❌ **I like that shoes.** (Giày là số nhiều -> **Those** shoes)',
            'This/That -> Số ít. These/Those -> Số nhiều.',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'this-that-these-those'),
            'vi',
            'This, That, These, Those',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating he-she-it-the-s-rule (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## The Lonely Third Person

In Present Simple, **I, You, We, They** change nothing. But **He, She, It** gets lonely, so they bring a snake (**S**)!

**He/She/It + Verb-S**',
        theory_formation = '*   I work -> He work**s**
*   You play -> She play**s**
*   It rain**s**

**Special Cases:**
*   Have -> **Has**
*   Go -> **Goes**
*   Do -> **Does**',
        theory_usage = 'Present Simple tense only.',
        theory_common_mistakes = '*   ❌ He **have** a car. -> ✅ He **has**.
*   ❌ She **go** to school. -> ✅ She **goes**.
*   ❌ Does he **works**? (After ''Does'', eat the ''s'' -> Does he **work**?)',
        localized_tips = 'He, She, It loves the SSSS sound.'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'he-she-it-the-s-rule')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'He/She/It (The S Rule)'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'he-she-it-the-s-rule');

    -- Updating he-she-it-the-s-rule (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'he-she-it-the-s-rule')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Quy tắc thêm S (He/She/It)',
            '## Ngôi thứ 3 cô đơn

Ở thì hiện tại đơn, **I, You, We, They** giữ nguyên động từ. Nhưng **He, She, It** (Ngôi thứ 3 số ít) thì cần thêm **S**!

**He/She/It + Verb-S**',
            '*   I work -> He work**s**
*   You play -> She play**s**
*   Nó mưa -> It rain**s**

**Đặc biệt:**
*   Have (Có) -> **Has**
*   Go (Đi) -> **Goes**
*   Do (Làm) -> **Does**',
            'Thì hiện tại đơn.',
            '*   ❌ He **have** a car. -> ✅ He **has**.
*   ❌ Does he **works**? (Sau Does -> động từ nguyên mẫu -> Does he **work**?)',
            'He/She/It yêu tiếng xì (S).',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'he-she-it-the-s-rule'),
            'vi',
            'Quy tắc thêm S (He/She/It)',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating there-is-vs-it-is (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## Existence vs Definition

*   **There is**: Introduce something new (It exists).
*   **It is**: Talk about something specific (Identify it).

Think of ''There is'' as presenting a new character on stage.',
        theory_formation = '*   **There is** a dog in the garden. (Fact: A dog exists there)
*   Look at the dog. **It is** big. (Description: The dog is big)',
        theory_usage = 'There is = Introduction. It is = Identification.',
        theory_common_mistakes = '*   ❌ **Is a dog in the garden.** (Missing subject)
*   ❌ **It is a dog in the garden.** (Wrong, us There is for location)
*   ❌ **Have a dog in the garden.** (No! Don''t translate directly from ''Il y a'' or ''Hay'' or ''Có'')',
        localized_tips = 'Don''t use ''HAVE'' to say something exists. Use ''THERE IS''.'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'there-is-vs-it-is')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'There is vs It is'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'there-is-vs-it-is');

    -- Updating there-is-vs-it-is (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'there-is-vs-it-is')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'There is vs It is',
            '## Tồn tại hay Nhận diện

*   **There is**: Giới thiệu cái gì đó mới (Có một...)
*   **It is**: Nói về cái cụ thể (Nó là...)

Đừng dịch "Ở đây có" thành "Here have". Hãy dùng "There is"!',
            '*   **There is** a dog in the garden. (Có một con chó...)
*   Look at the dog. **It is** big. (Nó thì to)',
            'There is = Giới thiệu. It is = Nhận diện.',
            '*   ❌ **Have a dog in the garden.** (Sai lầm lớn nhất của người Việt!)
*   ✅ **There is a dog...**',
            'Cấm dùng ''HAVE'' để nói ''Có cái gì ở đâu''. Phải dùng ''THERE IS''.',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'there-is-vs-it-is'),
            'vi',
            'There is vs It is',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating frequency-adverbs (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## How Often?

Words like **Always, Usually, Never** tell us how often we do things. But where do we put them? It depends on the verb!',
        theory_formation = '1.  **Before Action Verbs**:
    *   I **always** eat breakfast.
    *   She **never** smoke**s**.
2.  **After ''To Be''** (The King Verb):
    *   I am **always** happy.
    *   He is **never** late.',
        theory_usage = 'Describing routines.',
        theory_common_mistakes = '*   ❌ I eat **always** breakfast. (Adverb too late)
*   ❌ I **always** am happy. (Adverb too early)',
        localized_tips = 'To Be is the King, it goes FIRST. Other verbs are servants, they go AFTER the adverb.'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'frequency-adverbs')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Frequency Adverbs'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'frequency-adverbs');

    -- Updating frequency-adverbs (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'frequency-adverbs')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Trạng từ chỉ tần suất',
            '## Bao lâu một lần?

Những từ như **Always (Luôn luôn), Usually (Thường), Never (Không bao giờ)**. Vị trí của chúng phụ thuộc vào động từ.',
            '1.  **Trước Động từ thường**:
    *   I **always** eat breakfast.
2.  **Sau động từ To Be** (Động từ Vua):
    *   I am **always** happy.
    *   He is **never** late.',
            'Mô tả thói quen.',
            '*   ❌ I eat **always** breakfast.
*   ❌ I **always** am happy.',
            'To Be là Vua -> Đi trước. Động từ thường là lính -> Đi sau trạng từ.',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'frequency-adverbs'),
            'vi',
            'Trạng từ chỉ tần suất',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

    -- Updating object-pronouns-placement (English)
    UPDATE grammar_lesson_translations
    SET 
        theory_definition = '## The Magnetic Bond

In English, the **Verb** and the **Object** are like magnets stuck together. You CANNOT separate them with other words (like time or adverbs).',
        theory_formation = '✅ **I [like] [pizza] very much.**
❌ I [like] very much [pizza].

✅ **He [speaks] [English] well.**
❌ He [speaks] well [English].',
        theory_usage = 'Standard sentence structure.',
        theory_common_mistakes = '*   Separating verb and object is the #1 sign of a non-native speaker.',
        localized_tips = 'Glue the Object to the Verb. Put everything else (time, place, degree) at the END.'
    WHERE language_code = 'en' 
    AND lesson_id IN (
        SELECT id FROM grammar_lessons 
        WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'object-pronouns-placement')
    );

    -- Ensure Topic Translations are correct
    UPDATE grammar_topic_translations
    SET title = 'Object Placement'
    WHERE language_code = 'en'
    AND topic_id = (SELECT id FROM grammar_topics WHERE slug = 'object-pronouns-placement');

    -- Updating object-pronouns-placement (Vietnamese)
    -- Get Lesson ID
    SELECT id INTO v_lesson_id 
    FROM grammar_lessons 
    WHERE topic_id = (SELECT id FROM grammar_topics WHERE slug = 'object-pronouns-placement')
    LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO grammar_lesson_translations (lesson_id, language_code, theory_title, theory_definition, theory_formation, theory_usage, theory_common_mistakes, localized_tips, rules, examples)
        VALUES (
            v_lesson_id,
            'vi',
            'Vị trí tân ngữ',
            '## Liên kết nam châm

Trong tiếng Anh, **Động từ** và **Tân ngữ** dính chặt với nhau như nam châm. Bạn KHÔNG ĐƯỢC tách chúng ra bằng trạng từ hay thời gian.',
            '✅ **I [like] [pizza] very much.** (Tôi rất thích pizza)
❌ I [like] very much [pizza]. (Dịch từng chữ từ tiếng Việt -> Sai!)

✅ **He [speaks] [English] well.**
❌ He [speaks] well [English].',
            'Cấu trúc câu chuẩn.',
            '*   Chèn trạng từ vào giữa động từ và tân ngữ.',
            'Động từ + Tân ngữ là cặp bài trùng. Đừng chia cắt chúng. Đẩy mọi thứ khác (rất nhiều, hôm qua...) ra cuối câu.',
            '[]'::jsonb,
            '[]'::jsonb
        )
        ON CONFLICT (lesson_id, language_code) DO UPDATE SET
            theory_title = EXCLUDED.theory_title,
            theory_definition = EXCLUDED.theory_definition,
            theory_formation = EXCLUDED.theory_formation,
            theory_usage = EXCLUDED.theory_usage,
            theory_common_mistakes = EXCLUDED.theory_common_mistakes,
            localized_tips = EXCLUDED.localized_tips;
            
        -- Topic Translation
        INSERT INTO grammar_topic_translations (topic_id, language_code, title, description)
        VALUES (
            (SELECT id FROM grammar_topics WHERE slug = 'object-pronouns-placement'),
            'vi',
            'Vị trí tân ngữ',
            'Đã được dịch sang tiếng Việt.'
        )
        ON CONFLICT (topic_id, language_code) DO UPDATE SET
            title = EXCLUDED.title;
    END IF;

END $$;
