// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://cuumxmfzhwljylbdlflj.supabase.co';

const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1dW14bWZ6aHdsanlsYmRsZmxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTkxMjEsImV4cCI6MjA2OTA5NTEyMX0.8jqO_ciOttSxSLZnKY0i5oJmEn79ROF53TjUMYhNemI';

// Request timeout in milliseconds (120 seconds for longer edge function calls like speaking evaluation)
const REQUEST_TIMEOUT = 120000;

// Custom fetch with timeout to prevent hanging requests and retry on connection errors
const fetchWithTimeout = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), REQUEST_TIMEOUT);

  try {
    const response = await fetch(url, {
      ...options,
      signal: controller.signal,
    });
    return response;
  } catch (error: any) {
    // Retry once for connection closed or network errors
    if (error.name !== 'AbortError' && (error.message === 'Failed to fetch' || error.message.includes('ERR_CONNECTION_CLOSED') || error.message.includes('NetworkError'))) {
      console.log('Retrying fetch due to connection error...', error.message);
      // Small delay before retry
      await new Promise(resolve => setTimeout(resolve, 1000));
      return fetch(url, options);
    }
    throw error;
  } finally {
    clearTimeout(timeoutId);
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    fetch: fetchWithTimeout,
    headers: {
      'X-Client-Info': 'supabase-js-web',
    }
  }
});

// Create an admin client that includes custom headers for admin operations
// Note: Using a single supabase client instance to avoid "Multiple GoTrueClient instances" warning
// export const adminSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   },
//   global: {
//     headers: {
//       'X-Admin-Session': localStorage.getItem('admin_session') === 'true' ? 'true' : 'false',
//     },
//   },
// });

// Use the main supabase client for all operations
export const adminSupabase = supabase;